---
- name: test
  vars:
    client: z1aa
  hosts: oracle

  tasks:
    - block:
      - name: Display hostname
        command: hostname
        register: result

      - name: Display result
        debug:
          var: result.stdout
      when: client is match oracle
